language: java
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk: openjdk11
install:
- ./gradlew assemble
script:
  - ./gradlew check
  - ./gradlew createMacAppDistZip
  - ./gradlew createLinuxDistZip
  - ./gradlew createWinDistZip

notifications:
  email: false

before_deploy:
 - rm build/distributions/*.tar
# - git config --local user.name "igv.umccr.org"
# - git config --local user.email "services+igv@umccr.org"
# - export TRAVIS_TAG=${UMCCR-AWS-IGV-$(git log --format=%h -1)}
# - git tag -f $TRAVIS_TAG
# - git push origin $TRAVIS_TAG


deploy:
  provider: releases
  api_key:
    secure: G27mYWVwzS0eQXP8lyz7moM6xLYU7/rB5qTDx/L3niUggzT8ZmCFRA7YfRSoSXtkzozExLUmYG1DDDr/ed028lQ9eW+NJBHHtGsWMMFEAPwXOIptMKAl6bkuvnzQmrnE6p3upxR/CmkNvYRJLAFwRVJquxcsiDK9pSLHzj9/34iFCBXdqle3EJF77cZuWG7nl+dG7XLCVhUiad7d5niwyxTFLWEQWPC1ezle+jJU+QYuOwZ3gLFKaUsy01q2x1jD58HpnF6aAXVADGr2L2xrkjJGP14exVvVbUyB4Z0YW1Ency5JztFVe12zTpuz6Z5LPTWvybEfZdSoMEqiSkgtVBRN861tlt/0nwOsQ1PQOWkBTe96aN4BvlezySbDVc8kY9WdlwgNFk5WEMl64r5rOfGo79W1o7Yd/OE7aUsJSZyYh2a/3W6CB9RibAMoPNsdMg5YYYqVIbv+M3/zT7utmwxo+/IV9pENaHeBa9TkZqrhYd/ZNnjBRd5Sx5ZtWo3lNloaa5ODpVxbIxdQ36gmo3RKyvBwjQohqZ+MZHmnS2cffb0AkDqG5DdSNtoqvmckqJO/Oibhl7rP7otQ75WJ/1YAV+Kh2zBKbq/PoOX8DqnonruQcngwn+lPCIinHKyJuGeHjWql8UdhRFejnZwFUozcyMRqmEEoaowfZtz5hxc=
  file_glob: true
  file: "build/distributions/*-*-*.zip"
  skip_cleanup: true
  on:
      tags: true
